name: Deploy to jeffersonding.com

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions: 
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.3.0
          run_install: true
          
      - name: Build project
        run: pnpm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
